###################################################################################################
############################# ShamanOps pipeline | GitHub Actions##################################
###################################################################################################
name: ShamanOps
on:
  push:
    branches: [ "main" ]
jobs:
  shamanops:
    uses: shamanops/resources/.github/workflows/base-cloud-stable.yaml@main
    with:
    ## Environments:
    ## full-with-drp (dev/stg/prod/drp) | full (dev/stg/prod) | mid (stg/prod) | minimal (prod)
      environments: 'minimal'
    # Project
      projectName: 'examples'
    # Approvals
      shamanopsBusinessApprovers: 'jroca@customer.com'
      shamanopsTechnicalApprovers: 'jroca@shamanops.com'
      shamanopsBusinessApproversMinimalProd: '0'
      shamanopsTechnicalApproversMinimalProd: '1'
    # Feature flags
      security_check_enabled: 'true'
      security_check_report_upload: 'true'
      sbom_check_enabled: 'true'
      sbom_check_report_upload: 'true'
    # Verbosity level
      log_level: 'normal'
    secrets:
      shamanops_customer_token: ${{ secrets.shamanops_customer_token }}
      shamanops_argocd_dev_token: ${{ secrets.shamanops_argocd_dev_token }}
      shamanops_argocd_stg_token: ${{ secrets.shamanops_argocd_stg_token }}
      shamanops_argocd_prod_token: ${{ secrets.shamanops_argocd_prod_token }}
      shamanops_argocd_drp_token: ${{ secrets.shamanops_argocd_drp_token }}
      shamanops_code_quality_token: ${{ secrets.shamanops_code_quality_token }}
      shamanops_manifest_repository_token: ${{ secrets.shamanops_manifest_repository_token }}
      shamanops_chat_webhook: ${{ secrets.shamanops_chat_webhook }}
      shamanops_registry_password: ${{ secrets.shamanops_registry_password }}
      shamanops_dockerfile_token: ${{ secrets.shamanops_dockerfile_token }}
##################################################################################################
##################################################################################################
